### ISSUE TITLE
#14 - Implementar Navbar

### ISSUE THREAD

**Issue by Lucwar** [pgPilfs/pil-money-g3c-aula-3-grupo-3#14]
Crear  2 componentes "Navbar"
Crear navbar con botones de Inicio de sesión y registro.
Crear navbar con botones de home, transacciones, depositar, retirar, perfil.
Tiene que ser responsive (usar filas y columnas de bootstrap)

**Comment by Leandro-arg** [comment]
#15

**Comment by Leandro-arg** [comment]
> Crear 2 componentes "Navbar"
> Crear navbar con botones de Inicio de sesión y registro.
> Crear navbar con botones de home, transacciones, depositar, retirar, perfil.
> Tiene que ser responsive (usar filas y columnas de bootstrap)
